### ISSUE TITLE
Feature: Set log level

### ISSUE THREAD

**Issue by jryberg** [grafana/pyroscope-go#88]
It seems not possible to set log level. I got info and debug logs when I configure Logger to "pyroscope.StandardLogger" and nothing when I set Logger to nil.

I would like to be able to set log level to for example "info" since debug is quite verbose.

**Comment by kolesnikovae** [comment]
Hello @jryberg. Due to a very wide variance of log drivers, options, and requirements (such as level, format, decorating, output destination, etc), we recommend providing own implementation of [the interface](https://github.com/grafana/pyroscope-go/blob/a66d95c8e391f35ee0d950bab46e9f37f42fdf1e/types.go#L5-L12), if the standard logger does not meet requirements. Or, use the existing implementations, such as [logrus](https://github.com/sirupsen/logrus).

In the meantime, I think it would be nice to have support for the new Go structured logger https://pkg.go.dev/log/slog (Go 1.21 and higher)

**Comment by jryberg** [comment]
> Hello @jryberg. Due to the very wide variety of log drivers, options, and requirements (such as level, format, decorating, output destination, etc), we recommend providing own implementation of [the interface](https://github.com/grafana/pyroscope-go/blob/a66d95c8e391f35ee0d950bab46e9f37f42fdf1e/types.go#L5-L12), if the standard logger does not meet requirements. Or, use the existing implementations, such as [logrus](https://github.com/sirupsen/logrus).
> 
> In the meantime, I think it would be nice to have support for the new Go structured logger https://pkg.go.dev/log/slog (Go 1.21 and higher)

Thank you @kolesnikovae for your reply.

I'm already using logrus for logging but changing logrus log level does not change pyroscope-go log level since it always seems to use debug level. 

Do you know about any example where pyroscope-go logging has been modified?

**Comment by kolesnikovae** [comment]
Thank you @jryberg,

`logrus` logger already implements our interface, therefore you can provide it directly to the profiler:
```go
logger := logrus.New()
logger.SetLevel(logrus.InfoLevel)

Start(Config{
	ApplicationName: "my-app",
	ServerAddress:   "http://localhost:4040",
	Logger:          logger, // logger.WithField("component", "profiler")
})
```

**Comment by jryberg** [comment]
> Thank you @jryberg,
> 
> `logrus` logger already implements our interface, therefore you can provide it directly to the profiler:
> 
> ```go
> logger := logrus.New()
> logger.SetLevel(logrus.InfoLevel)
> 
> pyroscope.Start(pyroscope.Config{
> 	ApplicationName: "my-app",
> 	ServerAddress:   "http://localhost:4040",
> 	Logger:          logger, // logger.WithField("component", "profiler")
> })
> ```

Oh, that was embarrassing... I was hyper focused to create the log integration as an interface and did not realized that I could simply create a new logrus instance.

Thanks 🥇
